[package]
name = "beach_app"
version = "0.0.0"
edition = "2021"

[dependencies]
beach_civil = { path = "../beach_civil" }
beach_geography = { path = "../beach_geography" }
beach_ui = { path = "../beach_ui" }
bevy = { workspace = true, features = ["dynamic_linking"] }