[package]
name = "geometrician_environment"
version = "0.0.0"
edition = "2021"

[dependencies]
geometrician_core = { path = "../core" }
bevy = { workspace = true, features = ["dynamic_linking"] }

[lints]
workspace = true