[package]
name = "geometrician_infrastructure"
version = "0.0.0"
edition = "2021"

[dependencies]
geometrician_core = { path = "../core" }
geometrician_ui = { path = "../ui" }
bevy = { workspace = true, features = ["dynamic_linking"] }