[package]
name = "beach_ui"
version = "0.0.0"
edition = "2021"

[dependencies]
beach_core = { path = "../beach_core" }
bevy = { workspace = true, features = ["dynamic_linking"] }
bevy_mod_picking = { workspace = true }